### PR TITLE
Issues #1 and #2 - Fix for ESP32 and abstract SPI

### PR DESCRIPTION
**Pull request by rickyelopez**
Issue #1 - Fix all bugs preventing this from compiling for ESP32
Issue #2 - Abstract out the SPI bus so we can use with SPI2 instead

### CODE REVIEW

**Comment by johnstonstott** [comment]
@rickyelopez Is it just header files for now, or did you want me to try and run this on an ESP32?

**Comment by rickyelopez** [comment]
It's confirmed working, I tested. Just have a glance at my code and make sure there's no stupid mistakes please lol

**Review by johnstonstott — APPROVED** [review]
Nothing stupid stands out to me so approved!

**Review by Alessandro100 — APPROVED** [review]
Looks good!

**Pull request merged**
